//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTLCareerPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class jobApplying
    {
        public int pk { get; set; }
        public int JobId { get; set; }
        public int App_Id { get; set; }
        public System.DateTime ApplyDate { get; set; }
    
        public virtual JobSetup JobSetup { get; set; }
        public virtual tbl_SignUp tbl_SignUp { get; set; }
    }
}
