//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTLCareerPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobSetup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JobSetup()
        {
            this.jobApplyings = new HashSet<jobApplying>();
            this.tbl_AdminToHod = new HashSet<tbl_AdminToHod>();
        }
    
        public string JobTitle { get; set; }
        public string TotalPosition { get; set; }
        public string JobType { get; set; }
        public string Education { get; set; }
        public Nullable<int> Department { get; set; }
        public string JobRequirements { get; set; }
        public string SkillsRequired { get; set; }
        public Nullable<System.DateTime> JobOpeningDate { get; set; }
        public Nullable<System.DateTime> JobClosingDate { get; set; }
        public string JobStatus { get; set; }
        public string JobLocation { get; set; }
        public string ScopeOfResponsibility { get; set; }
        public string Experience { get; set; }
        public string CompensationBenefits { get; set; }
        public int pk { get; set; }
    
        public virtual citySetup citySetup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<jobApplying> jobApplyings { get; set; }
        public virtual tbl_Department tbl_Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_AdminToHod> tbl_AdminToHod { get; set; }
    }
}
