//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTLCareerPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ProfessionalReference
    {
        public int PR_Id { get; set; }
        public string Name { get; set; }
        public string Relationship { get; set; }
        public string Designation { get; set; }
        public string Organization { get; set; }
        public string ContactNo { get; set; }
        public Nullable<int> App_Id { get; set; }
    
        public virtual tbl_SignUp tbl_SignUp { get; set; }
    }
}
