//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTLCareerPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Education
    {
        public int Edu_Id { get; set; }
        public string Degree { get; set; }
        public Nullable<int> CompletionYear { get; set; }
        public string Institute { get; set; }
        public string Specialization { get; set; }
        public string CGPA { get; set; }
        public Nullable<int> App_Id { get; set; }
    
        public virtual tbl_SignUp tbl_SignUp { get; set; }
    }
}
