//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTLCareerPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_FOI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_FOI()
        {
            this.tbl_JobSalaryPreference = new HashSet<tbl_JobSalaryPreference>();
            this.tbl_JobSalaryPreference1 = new HashSet<tbl_JobSalaryPreference>();
            this.tbl_JobSalaryPreference2 = new HashSet<tbl_JobSalaryPreference>();
        }
    
        public int FOI_Id { get; set; }
        public string FOI_Name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_JobSalaryPreference> tbl_JobSalaryPreference { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_JobSalaryPreference> tbl_JobSalaryPreference1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_JobSalaryPreference> tbl_JobSalaryPreference2 { get; set; }
    }
}
