//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTLCareerPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SignUp
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_SignUp()
        {
            this.jobApplyings = new HashSet<jobApplying>();
            this.tbl_AdminToHod = new HashSet<tbl_AdminToHod>();
            this.tbl_CareerObjective = new HashSet<tbl_CareerObjective>();
            this.tbl_Education = new HashSet<tbl_Education>();
            this.tbl_Experience = new HashSet<tbl_Experience>();
            this.tbl_GeneralInfo = new HashSet<tbl_GeneralInfo>();
            this.tbl_Images = new HashSet<tbl_Images>();
            this.tbl_JobSalaryPreference = new HashSet<tbl_JobSalaryPreference>();
            this.tbl_PersonalInfo = new HashSet<tbl_PersonalInfo>();
            this.tbl_ProfessionalReference = new HashSet<tbl_ProfessionalReference>();
            this.tbl_Resumes = new HashSet<tbl_Resumes>();
        }
    
        public int ApplicantId { get; set; }
        public string Name { get; set; }
        public string FatherName { get; set; }
        public string Gender { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string EmailID { get; set; }
        public string CellNo { get; set; }
        public string UserType { get; set; }
        public string Password { get; set; }
        public Nullable<int> Dep_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<jobApplying> jobApplyings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_AdminToHod> tbl_AdminToHod { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_CareerObjective> tbl_CareerObjective { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Education> tbl_Education { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Experience> tbl_Experience { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_GeneralInfo> tbl_GeneralInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Images> tbl_Images { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_JobSalaryPreference> tbl_JobSalaryPreference { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_PersonalInfo> tbl_PersonalInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ProfessionalReference> tbl_ProfessionalReference { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Resumes> tbl_Resumes { get; set; }
    }
}
